Calculate the Taylor Polynomials:
$$T_n (x) = \sum_{k=0}^{n} \frac{f^{(k)}(0)}{k!}(x)^k$$
centered at 0 for the following functions at the values of x,$$ x \in\ \{ \frac{1}{32}, \frac{1}{16}, \frac{1}{8}, \frac{1}{4}, \frac{1}{2}, 1, 2, 4 \} $$ 
and for
$$ n \in\ \{ 1, 2, 3, 4, 8, 16, 32, 64, 128, 256 \} $$

functions:

$$sin(x)$$
$$cos(x)$$
$$exp(x)$$
$$log_e(1-x)\textrm{   } x<1$$

In [2]:
import math
from decimal import *
arr_x = [1/32, 1/16, 1/8, 1/4, 1/2, 1 ,2 ,4]
arr_n = [1, 2, 3, 4, 8, 16, 32, 64, 128, 256]
#For sin derivatives
sin_der = [0,1,0,-1]
#For cos derivatives
cos_der = [1,0,-1,0]
#For log(1-x) x<1 derivatives
log_der = [0, -1]
temp = 1
for i in range (1,256):
    log_der += [i*log_der[temp]]
    temp += 1

sin_sum_arr = []
cos_sum_arr = []
ex_sum_arr = []
log_sum_arr = []

true_sin = []
true_cos = []
true_ex = []
true_log = []

abs_err_sin = []
abs_err_cos = []
abs_err_ex = []
abs_err_log = []

rel_err_sin = []
rel_err_cos = []
rel_err_ex = []
rel_err_log = []

for i in arr_n:
    for j in arr_x:
        curr_sin_sum = 0
        curr_cos_sum = 0
        curr_ex_sum = 0
        curr_log_sum = 0
        temp = 0
        temp2 = 0
        for index in range (0,i+1):
            temp2 = (Decimal(math.pow(j,index)))/(Decimal(math.factorial(index)))
            curr_sin_sum += (sin_der[temp])*temp2
            curr_cos_sum += (cos_der[temp])*temp2
            #Derivative of exponential is itself. e^0 is always 1, so we set the exponential_sum equal to temp2.
            curr_ex_sum += temp2
            if(j<1):
                curr_log_sum += (log_der[index])*temp2
            temp += 1
            if temp == 4:
                temp = 0            
        sin_sum_arr += [curr_sin_sum]
        cos_sum_arr += [curr_cos_sum]
        ex_sum_arr += [curr_ex_sum]
        if(j<1):
            log_sum_arr += [curr_log_sum]
            
for i in arr_x:
    true_sin += [math.sin(i)]
    true_cos += [math.cos(i)]
    true_ex += [math.exp(i)]
    #Omitting the second argument of the log function automatically makes the base e.
    if(i<1):
        true_log += [math.log(1-i)]
temp = 0
for i in range(0,80):
    abs_err_sin += [abs(Decimal(true_sin[temp]) - sin_sum_arr[i])]
    abs_err_cos += [abs(Decimal(true_cos[temp]) - cos_sum_arr[i])]
    abs_err_ex += [abs(Decimal(true_ex[temp]) - ex_sum_arr[i])]
    rel_err_sin += [abs_err_sin[i]/Decimal(true_sin[temp])]
    rel_err_cos += [abs_err_cos[i]/Decimal(true_cos[temp])]
    rel_err_ex += [abs_err_ex[i]/Decimal(true_ex[temp])]
    temp += 1
    if temp % 8 == 0:
        temp = 0
temp = 0
for i in range(0,50):
    abs_err_log += [abs(Decimal(true_log[temp]) - log_sum_arr[i])]
    rel_err_log += [abs_err_log[i]/Decimal(true_log[temp])]
    temp += 1
    if temp % 5 == 0:
        temp = 0

In [7]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[0])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 1/32:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 0
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 1/32:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,0.03125,0.03124491398532608,0.000005086014673919697637316517103,0.0001627789622435287566399701006
N = 2,0.03125000000,0.03124491398532608,0.000005086014673919697637316517103,0.0001627789622435287566399701006
N = 3,0.03124491373697916666666666667,0.03124491398532608,2.483469136356960168128974097E-10,7.948394857234368597496154329E-9
N = 4,0.03124491373697916666666666667,0.03124491398532608,2.483469136356960168128974097E-10,7.948394857234368597496154329E-9
N = 8,0.03124491398532607866125920463,0.03124491398532608,1.641103478852897409703582525E-18,5.252385971117181853389917243E-17
N = 16,0.03124491398532607873958112126,0.03124491398532608,1.562781562222897409703582525E-18,5.001715040588189995543406641E-17
N = 32,0.03124491398532607873958112126,0.03124491398532608,1.562781562222897409703582525E-18,5.001715040588189995543406641E-17
N = 64,0.03124491398532607873958112126,0.03124491398532608,1.562781562222897409703582525E-18,5.001715040588189995543406641E-17
N = 128,0.03124491398532607873958112126,0.03124491398532608,1.562781562222897409703582525E-18,5.001715040588189995543406641E-17
N = 256,0.03124491398532607873958112126,0.03124491398532608,1.562781562222897409703582525E-18,5.001715040588189995543406641E-17

In [3]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[1])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 1/16:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 1
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 1/16:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,0.0625,0.0624593178423802,0.00004068215761979937505898874406,0.0006513384875970502399544316248
N = 2,0.062500000,0.0624593178423802,0.00004068215761979937505898874406,0.0006513384875970502399544316248
N = 3,0.06245930989583333333333333333,0.0624593178423802,7.946546867291607677925941703E-9,1.272275641457562955387616826E-7
N = 4,0.06245930989583333333333333333,0.0624593178423802,7.946546867291607677925941703E-9,1.272275641457562955387616826E-7
N = 8,0.06245931784238015848492819165,0.0624593178423802,4.214001281960594170298427343E-17,6.746793637091709463320789434E-16
N = 16,0.06245931784238019858468150667,0.0624593178423802,2.040259504585941702984273434E-18,3.266541446601542747586156417E-17
N = 32,0.06245931784238019858468150667,0.0624593178423802,2.040259504585941702984273434E-18,3.266541446601542747586156417E-17
N = 64,0.06245931784238019858468150667,0.0624593178423802,2.040259504585941702984273434E-18,3.266541446601542747586156417E-17
N = 128,0.06245931784238019858468150667,0.0624593178423802,2.040259504585941702984273434E-18,3.266541446601542747586156417E-17
N = 256,0.06245931784238019858468150667,0.0624593178423802,2.040259504585941702984273434E-18,3.266541446601542747586156417E-17

In [4]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[2])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 1/8:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 2
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 1/8:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,0.125,0.12467473338522769,0.0003252666147723071166097952300,0.002608921679160750536624280939
N = 2,0.1250000,0.12467473338522769,0.0003252666147723071166097952300,0.002608921679160750536624280939
N = 3,0.1246744791666666666666666667,0.12467473338522769,2.542185610262167235380699667E-7,0.000002039054378730584564844524831
N = 4,0.1246744791666666666666666667,0.12467473338522769,2.542185610262167235380699667E-7,0.000002039054378730584564844524831
N = 8,0.1246747333852071610708085318,0.12467473338522769,2.053181258167296996665820479E-14,1.646830277810380962878632670E-13
N = 16,0.1246747333852276899574427088,0.12467473338522769,2.925947495969966658204793930E-18,2.346864851059431053585922595E-17
N = 32,0.1246747333852276899574427088,0.12467473338522769,2.925947495969966658204793930E-18,2.346864851059431053585922595E-17
N = 64,0.1246747333852276899574427088,0.12467473338522769,2.925947495969966658204793930E-18,2.346864851059431053585922595E-17
N = 128,0.1246747333852276899574427088,0.12467473338522769,2.925947495969966658204793930E-18,2.346864851059431053585922595E-17
N = 256,0.1246747333852276899574427088,0.12467473338522769,2.925947495969966658204793930E-18,2.346864851059431053585922595E-17

In [5]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[3])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 1/4:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 3
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 1/4:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,0.25,0.24740395925452294,0.002596040745477062872126339244,0.01049312530526773744869126687
N = 2,0.25000,0.24740395925452294,0.002596040745477062872126339244,0.01049312530526773744869126687
N = 3,0.2473958333333333333333333333,0.24740395925452294,0.000008125921189603794540327456450,0.00003284474999546814973260063260
N = 4,0.2473958333333333333333333333,0.24740395925452294,0.000008125921189603794540327456450,0.00003284474999546814973260063260
N = 8,0.2474039592440166170634920634,0.24740395925452294,1.050632006438159735644968078E-11,4.246625678925760824070454170E-11
N = 16,0.2474039592545229295968485411,0.24740395925452294,7.531025119656449680775403976E-18,3.044019643965649505311509680E-17
N = 32,0.2474039592545229295968487047,0.24740395925452294,7.531024956056449680775403976E-18,3.044019577838979385334788941E-17
N = 64,0.2474039592545229295968487047,0.24740395925452294,7.531024956056449680775403976E-18,3.044019577838979385334788941E-17
N = 128,0.2474039592545229295968487047,0.24740395925452294,7.531024956056449680775403976E-18,3.044019577838979385334788941E-17
N = 256,0.2474039592545229295968487047,0.24740395925452294,7.531024956056449680775403976E-18,3.044019577838979385334788941E-17

In [6]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[4])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 1/2:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 4
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 1/2:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,0.5,0.479425538604203,0.02057446139579699462274220423,0.04291482146674408178336751744
N = 2,0.500,0.479425538604203,0.02057446139579699462274220423,0.04291482146674408178336751744
N = 3,0.4791666666666666666666666667,0.479425538604203,0.0002588719375363387105911290716,0.0005399627610369216242727957250
N = 4,0.4791666666666666666666666667,0.479425538604203,0.0002588719375363387105911290716,0.0005399627610369216242727957250
N = 8,0.4794255332341269841269841271,0.479425538604203,5.370076021250273668671583915E-9,1.120106374993014512201795364E-8
N = 16,0.4794255386042030002518538891,0.479425538604203,5.125403906671583914756774902E-18,1.069071940054269516886670859E-17
N = 32,0.4794255386042030002732879354,0.479425538604203,5.103969860371583914756774902E-18,1.064601163140214631574831721E-17
N = 64,0.4794255386042030002732879354,0.479425538604203,5.103969860371583914756774902E-18,1.064601163140214631574831721E-17
N = 128,0.4794255386042030002732879354,0.479425538604203,5.103969860371583914756774902E-18,1.064601163140214631574831721E-17
N = 256,0.4794255386042030002732879354,0.479425538604203,5.103969860371583914756774902E-18,1.064601163140214631574831721E-17

In [7]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[5])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 1:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 5
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 1:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1,0.8414709848078965,0.1585290151921034951243427713,0.1883951057781212187710074418
N = 2,1.0,0.8414709848078965,0.1585290151921034951243427713,0.1883951057781212187710074418
N = 3,0.8333333333333333333333333333,0.8414709848078965,0.008137651474563171542323895395,0.009670745184898984357493798516
N = 4,0.8333333333333333333333333333,0.8414709848078965,0.008137651474563171542323895395,0.009670745184898984357493798516
N = 8,0.8414682539682539682539682539,0.8414709848078965,0.000002730839642536621688974794763,0.000003245316465855395269333256930
N = 16,0.8414709848078937033963488989,0.8414709848078965,2.801479308329794763034582138E-15,3.329264298957804315804271200E-15
N = 32,0.8414709848078965066525023216,0.8414709848078965,1.776845092905236965417861938E-18,2.111594012134454707826348342E-18
N = 64,0.8414709848078965066525023216,0.8414709848078965,1.776845092905236965417861938E-18,2.111594012134454707826348342E-18
N = 128,0.8414709848078965066525023216,0.8414709848078965,1.776845092905236965417861938E-18,2.111594012134454707826348342E-18
N = 256,0.8414709848078965066525023216,0.8414709848078965,1.776845092905236965417861938E-18,2.111594012134454707826348342E-18

In [8]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[6])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 2:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 6
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 2:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,2,0.9092974268256817,1.090702573174318290583073576,1.199500340589232899598211665
N = 2,2,0.9092974268256817,1.090702573174318290583073576,1.199500340589232899598211665
N = 3,0.666666666666666666666666667,0.9092974268256817,0.2426307601590150427502597567,0.2668332198035890334672627778
N = 4,0.6666666666666666666666666670,0.9092974268256817,0.2426307601590150427502597567,0.2668332198035890334672627778
N = 8,0.9079365079365079365079365083,0.9092974268256817,0.001360918889173772908989915428,0.001496670780126017007795973761
N = 16,0.9092974264614476254687894903,0.9092974268256817,3.642340839481369334280003726E-10,4.005664958490672164293516770E-10
N = 32,0.9092974268256816953960198652,0.9092974268256817,1.402090655852800037264823914E-17,1.541949437542607307281848269E-17
N = 64,0.9092974268256816953960198662,0.9092974268256817,1.402090655752800037264823914E-17,1.541949437432632290252386624E-17
N = 128,0.9092974268256816953960198662,0.9092974268256817,1.402090655752800037264823914E-17,1.541949437432632290252386624E-17
N = 256,0.9092974268256816953960198662,0.9092974268256817,1.402090655752800037264823914E-17,1.541949437432632290252386624E-17

In [31]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(sin_sum_arr[0])],
    'Exact Value':[str(true_sin[7])],
    'Absolute Error':[str(abs_err_sin[0])],
    'Relative Error':[str(rel_err_sin[0])] 
}
print('For sin(x) when x = 4:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 7
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (sin_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_sin[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_sin[temp])
    temp = temp + 8
df

For sin(x) when x = 4:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,4,-0.7568024953079282,4.756802495307928202450398203,-6.285394835243609852452741518
N = 2,4,-0.7568024953079282,4.756802495307928202450398203,-6.285394835243609852452741518
N = 3,-6.66666666666666666666666667,-0.7568024953079282,5.909864171358738464216268467,-7.808991392072683087421235868
N = 4,-6.66666666666666666666666667,-0.7568024953079282,5.909864171358738464216268467,-7.808991392072683087421235868
N = 8,-1.384126984126984126984126988,-0.7568024953079282,0.6273244888190559245337287851,-0.8289144033065189648169804035
N = 16,-0.7568486195364502242809121155,-0.7568024953079282,0.00004612422852202183051391257268,-0.00006094618980247254581505629435
N = 32,-0.7568024953079282597572998146,-0.7568024953079282,5.730690161167268252968788147E-17,-7.572240045053712444978760505E-17
N = 64,-0.7568024953079282513726390986,-0.7568024953079282,4.892224089567268252968788147E-17,-6.464333983963302749481484053E-17
N = 128,-0.7568024953079282513726390986,-0.7568024953079282,4.892224089567268252968788147E-17,-6.464333983963302749481484053E-17
N = 256,-0.7568024953079282513726390986,-0.7568024953079282,4.892224089567268252968788147E-17,-6.464333983963302749481484053E-17

In [10]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[0])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 1/32:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 0
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 1/32:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.00000,0.9995117584851364,0.0004882415148635965707057948748,0.0004884800110841889015389748950
N = 2,0.99951171875,0.9995117584851364,3.973513640342929420512518845E-8,3.975454622330007310468253628E-8
N = 3,0.9995117187500000000000000000,0.9995117584851364,3.973513640342929420512518845E-8,3.975454622330007310468253628E-8
N = 4,0.9995117584864298502604166667,0.9995117584851364,1.293446831122461574811545014E-12,1.294078654044865083851867303E-12
N = 8,0.9995117584851363692414740818,0.9995117584851364,3.418782012332518845498561859E-17,3.420452019007797459942088185E-17
N = 16,0.9995117584851363692412293254,0.9995117584851364,3.418806487972518845498561859E-17,3.420476506603658358434705431E-17
N = 32,0.9995117584851363692412293254,0.9995117584851364,3.418806487972518845498561859E-17,3.420476506603658358434705431E-17
N = 64,0.9995117584851363692412293254,0.9995117584851364,3.418806487972518845498561859E-17,3.420476506603658358434705431E-17
N = 128,0.9995117584851363692412293254,0.9995117584851364,3.418806487972518845498561859E-17,3.420476506603658358434705431E-17
N = 256,0.9995117584851363692412293254,0.9995117584851364,3.418806487972518845498561859E-17,3.420476506603658358434705431E-17

In [11]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[1])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 1/16:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 1
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 1/16:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.0000,0.9980475107000991,0.001952489299900883601424084191,0.001956308972236475414440662820
N = 2,0.998046875,0.9980475107000991,6.357000991163985759158094879E-7,6.369437249239516031666001299E-7
N = 3,0.9980468750000000000000000000,0.9980475107000991,6.357000991163985759158094879E-7,6.369437249239516031666001299E-7
N = 4,0.9980475107828776041666666667,0.9980475107000991,8.277848776809075089051207602E-11,8.294042806641963415899113238E-11
N = 8,0.9980475107000991498814925315,0.9980475107000991,3.348291661569051207602024078E-17,3.354841954588243318735321109E-17
N = 16,0.9980475107000991496308675899,0.9980475107000991,3.323229167409051207602024078E-17,3.329730430446051486468107707E-17
N = 32,0.9980475107000991496308675899,0.9980475107000991,3.323229167409051207602024078E-17,3.329730430446051486468107707E-17
N = 64,0.9980475107000991496308675899,0.9980475107000991,3.323229167409051207602024078E-17,3.329730430446051486468107707E-17
N = 128,0.9980475107000991496308675899,0.9980475107000991,3.323229167409051207602024078E-17,3.329730430446051486468107707E-17
N = 256,0.9980475107000991496308675899,0.9980475107000991,3.323229167409051207602024078E-17,3.329730430446051486468107707E-17

In [12]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[2])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 1/8:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 2
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 1/8:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.000,0.992197667229329,0.007802332770670994399608844105,0.007863687880317927292267747390
N = 2,0.9921875,0.992197667229329,0.00001016722932900560039115589461,0.00001024718124705651470309438645
N = 3,0.9921875000000000000000000000,0.992197667229329,0.00001016722932900560039115589461,0.00001024718124705651470309438645
N = 4,0.9921976725260416666666666667,0.992197667229329,5.296712661066275510805387107E-9,5.338364356224628898930701334E-9
N = 8,0.9921976672293293097662547278,0.992197667229329,3.041658635719053871065378189E-16,3.065577289868822156370399056E-16
N = 16,0.9921976672293290531490969079,0.992197667229329,4.754870575200538710653781891E-17,4.792261393315223518609277956E-17
N = 32,0.9921976672293290531490969079,0.992197667229329,4.754870575200538710653781891E-17,4.792261393315223518609277956E-17
N = 64,0.9921976672293290531490969079,0.992197667229329,4.754870575200538710653781891E-17,4.792261393315223518609277956E-17
N = 128,0.9921976672293290531490969079,0.992197667229329,4.754870575200538710653781891E-17,4.792261393315223518609277956E-17
N = 256,0.9921976672293290531490969079,0.992197667229329,4.754870575200538710653781891E-17,4.792261393315223518609277956E-17

In [13]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[3])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 1/4:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 3
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 1/4:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.00,0.9689124217106447,0.03108757828935526656977117455,0.03208502398438569841936715304
N = 2,0.96875,0.9689124217106447,0.0001624217106447334302288254548,0.0001676330151263546562380704929
N = 3,0.9687500000000000000000000000,0.9689124217106447,0.0001624217106447334302288254548,0.0001676330151263546562380704929
N = 4,0.9689127604166666666666666667,0.9689124217106447,3.387060219332364378412451670E-7,3.495734127706201973734140289E-7
N = 8,0.9689124217109074668278769841,0.9689124217106447,2.627333976481586451670140028E-13,2.711632050131989603468224492E-13
N = 16,0.9689124217106447841445954517,0.9689124217106447,5.071436662624516701400279999E-17,5.234153829580117281255811455E-17
N = 32,0.9689124217106447841445954494,0.9689124217106447,5.071436662394516701400279999E-17,5.234153829342737725739402744E-17
N = 64,0.9689124217106447841445954494,0.9689124217106447,5.071436662394516701400279999E-17,5.234153829342737725739402744E-17
N = 128,0.9689124217106447841445954494,0.9689124217106447,5.071436662394516701400279999E-17,5.234153829342737725739402744E-17
N = 256,0.9689124217106447841445954494,0.9689124217106447,5.071436662394516701400279999E-17,5.234153829342737725739402744E-17

In [14]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[4])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 1/2:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 4
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 1/2:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.0,0.8775825618903728,0.1224174381096272412605685531,0.1394939273245490669694518266
N = 2,0.875,0.8775825618903728,0.002582561890372758739431446884,0.002942813591019566401729651740
N = 3,0.8750000000000000000000000000,0.8775825618903728,0.002582561890372758739431446884,0.002942813591019566401729651740
N = 4,0.8776041666666666666666666667,0.8775825618903728,0.00002160477629390792723521981617,0.00002461851138811346016996243015
N = 8,0.8775825621589781746031746032,0.8775825618903728,2.686054158637431563161725521E-10,3.060742402232204232116097507E-10
N = 16,0.8775825618903727161168770163,0.8775825618903728,4.262255443058382744789123535E-17,4.856814194071032471358862792E-17
N = 32,0.8775825618903727161162815826,0.8775825618903728,4.262314986428382744789123535E-17,4.856882043379559910094040509E-17
N = 64,0.8775825618903727161162815826,0.8775825618903728,4.262314986428382744789123535E-17,4.856882043379559910094040509E-17
N = 128,0.8775825618903727161162815826,0.8775825618903728,4.262314986428382744789123535E-17,4.856882043379559910094040509E-17
N = 256,0.8775825618903727161162815826,0.8775825618903728,4.262314986428382744789123535E-17,4.856882043379559910094040509E-17

In [15]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[5])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 1:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 5
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 1:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1,0.5403023058681398,0.4596976941318602349895172665,0.8508157176809254548243569362
N = 2,0.5,0.5403023058681398,0.04030230586813976501048273349,0.07459214115953727258782153191
N = 3,0.5000000000000000000000000000,0.5403023058681398,0.04030230586813976501048273349,0.07459214115953727258782153191
N = 4,0.5416666666666666666666666667,0.5403023058681398,0.001364360798526901656183933213,0.002525180410501288029860007163
N = 8,0.5403025793650793650793650794,0.5403023058681398,2.734969396000688823459128484E-7,5.061924345494382097186859119E-7
N = 16,0.5403023058681398731828626009,0.5403023058681398,1.081723798674128484368324280E-16,2.002071408775594029752795447E-16
N = 32,0.5403023058681397174009366074,0.5403023058681398,4.760954612608715156316757202E-17,8.811649628181711567475875510E-17
N = 64,0.5403023058681397174009366074,0.5403023058681398,4.760954612608715156316757202E-17,8.811649628181711567475875510E-17
N = 128,0.5403023058681397174009366074,0.5403023058681398,4.760954612608715156316757202E-17,8.811649628181711567475875510E-17
N = 256,0.5403023058681397174009366074,0.5403023058681398,4.760954612608715156316757202E-17,8.811649628181711567475875510E-17

In [16]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[6])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 2:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 6
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 2:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1,-0.4161468365471424,1.416146836547142406903532219,-3.402997961722380874809617784
N = 2,-1,-0.4161468365471424,0.5838531634528575930964677809,-1.402997961722380874809617784
N = 3,-1.000000000000000000000000000,-0.4161468365471424,0.5838531634528575930964677809,-1.402997961722380874809617784
N = 4,-0.3333333333333333333333333333,-0.4161468365471424,0.08281350321380907357019888578,-0.1990006794258730417301274053
N = 8,-0.4158730158730158730158730159,-0.4161468365471424,0.0002738206741265338876592031757,-0.0006579905218035092061589531179
N = 16,-0.4161468365066248664132262015,-0.4161468365471424,4.051754049030601757571423799E-11,-9.736356721220939684499284787E-11
N = 32,-0.4161468365471423869975682293,-0.4161468365471424,1.990596398977571423798799515E-17,-4.783399089355015384206675106E-17
N = 64,-0.4161468365471423869975682294,-0.4161468365471424,1.990596398967571423798799515E-17,-4.783399089330985404589451298E-17
N = 128,-0.4161468365471423869975682294,-0.4161468365471424,1.990596398967571423798799515E-17,-4.783399089330985404589451298E-17
N = 256,-0.4161468365471423869975682294,-0.4161468365471424,1.990596398967571423798799515E-17,-4.783399089330985404589451298E-17

In [17]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(cos_sum_arr[0])],
    'Exact Value':[str(true_cos[7])],
    'Absolute Error':[str(abs_err_cos[0])],
    'Relative Error':[str(rel_err_cos[0])] 
}
print('For cos(x) when x = 4:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 7
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (cos_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_cos[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_cos[temp])
    temp = temp + 8
df

For cos(x) when x = 4:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1,-0.6536436208636119,1.653643620863611940485782270,-2.529885656466397514134215172
N = 2,-7,-0.6536436208636119,6.346356379136388059514217730,-9.709199595264782598939506203
N = 3,-7.00000000000000000000000000,-0.6536436208636119,6.346356379136388059514217730,-9.709199595264782598939506203
N = 4,3.66666666666666666666666667,-0.6536436208636119,4.320310287530278607152448940,-6.609580740376790885158788968
N = 8,-0.396825396825396825396825394,-0.6536436208636119,0.2568182240382151150889568761,-0.3929025172752390816927717615
N = 16,-0.6536333241518426703611888769,-0.6536436208636119,0.00001029671176927012459339321603,-0.00001575279164457510597770921622
N = 32,-0.6536436208636119136520074946,-0.6536436208636119,2.683377477551603303253650665E-17,-4.105260713791180478463786839E-17
N = 64,-0.6536436208636119146391681803,-0.6536436208636119,2.584661408981603303253650665E-17,-3.954236416423184117557636110E-17
N = 128,-0.6536436208636119146391681803,-0.6536436208636119,2.584661408981603303253650665E-17,-3.954236416423184117557636110E-17
N = 256,-0.6536436208636119146391681803,-0.6536436208636119,2.584661408981603303253650665E-17,-3.954236416423184117557636110E-17

In [18]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[0])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 1/32:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 0
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 1/32:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.03125,1.0317434074991028,0.0004934074991027603829252257128,0.0004782269462702522449481918038
N = 2,1.03173828125,1.0317434074991028,0.000005126249102760382925225712825,0.000004968530998599902261140758243
N = 3,1.031743367513020833333333333,1.0317434074991028,3.998608192704959189271282461E-8,3.875583952019035815096626301E-8
N = 4,1.031743407249450683593750000,1.0317434074991028,2.496520767891752257128246129E-10,2.419710898801089085329113747E-10
N = 8,1.031743407499102670860179747,1.0317434074991028,8.952274547871282461285591125E-17,8.676842015953533163422130793E-17
N = 16,1.031743407499102670938747814,1.0317434074991028,8.944417741171282461285591125E-17,8.669226937783036752908529629E-17
N = 32,1.031743407499102670938747814,1.0317434074991028,8.944417741171282461285591125E-17,8.669226937783036752908529629E-17
N = 64,1.031743407499102670938747814,1.0317434074991028,8.944417741171282461285591125E-17,8.669226937783036752908529629E-17
N = 128,1.031743407499102670938747814,1.0317434074991028,8.944417741171282461285591125E-17,8.669226937783036752908529629E-17
N = 256,1.031743407499102670938747814,1.0317434074991028,8.944417741171282461285591125E-17,8.669226937783036752908529629E-17

In [19]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[1])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 1/16:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 1
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 1/16:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.0625,1.0644944589178593,0.001994458917859320834509162523,0.001873620760681875297849845672
N = 2,1.064453125,1.0644944589178593,0.00004133391785932083450916252332,0.00003882962237430521567677553558
N = 3,1.064493815104166666666666667,1.0644944589178593,6.438136926541678424955233181E-7,6.048069928975056315029279301E-7
N = 4,1.064494450887044270833333334,1.0644944589178593,8.030815050001175828523318082E-9,7.544252563010162045235190605E-9
N = 8,1.064494458917859389210149409,1.0644944589178593,6.837564024647668191790580750E-17,6.423296962577502873388212930E-17
N = 16,1.064494458917859429563390594,1.0644944589178593,1.087288814314766819179058075E-16,1.021413315218267756713388554E-16
N = 32,1.064494458917859429563390594,1.0644944589178593,1.087288814314766819179058075E-16,1.021413315218267756713388554E-16
N = 64,1.064494458917859429563390594,1.0644944589178593,1.087288814314766819179058075E-16,1.021413315218267756713388554E-16
N = 128,1.064494458917859429563390594,1.0644944589178593,1.087288814314766819179058075E-16,1.021413315218267756713388554E-16
N = 256,1.064494458917859429563390594,1.0644944589178593,1.087288814314766819179058075E-16,1.021413315218267756713388554E-16

In [20]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[2])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 1/8:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 2
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 1/8:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.125,1.1331484530668263,0.008148453066826322199744936370,0.007190984592330176482572913601
N = 2,1.1328125,1.1331484530668263,0.0003359530668263221997449363698,0.0002964775408880249303685588338
N = 3,1.133138020833333333333333333,1.1331484530668263,0.00001043223349298886641160336983,0.000009206413744601949026711012679
N = 4,1.133148193359375000000000000,1.1331484530668263,2.597074513221997449363698252E-7,2.291910213699808597779649064E-7
N = 8,1.133148453066805525431557308,1.1331484530668263,2.079676818762836982515454292E-14,1.835308350935188608795618086E-14
N = 16,1.133148453066826316829007229,1.1331484530668263,5.370737707369825154542922974E-18,4.739659391348161818422959745E-18
N = 32,1.133148453066826316829007229,1.1331484530668263,5.370737707369825154542922974E-18,4.739659391348161818422959745E-18
N = 64,1.133148453066826316829007229,1.1331484530668263,5.370737707369825154542922974E-18,4.739659391348161818422959745E-18
N = 128,1.133148453066826316829007229,1.1331484530668263,5.370737707369825154542922974E-18,4.739659391348161818422959745E-18
N = 256,1.133148453066826316829007229,1.1331484530668263,5.370737707369825154542922974E-18,4.739659391348161818422959745E-18

In [21]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[3])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 1/4:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 3
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 1/4:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.25,1.2840254166877414,0.03402541668774139438369275013,0.02649902116074384669407493771
N = 2,1.28125,1.2840254166877414,0.002775416687741394383692750125,0.002161496689762442861426811144
N = 3,1.283854166666666666666666667,1.2840254166877414,0.0001712500210747277170260831252,0.0001333696505139925420394670053
N = 4,1.284016927083333333333333334,1.2840254166877414,0.000008489604408061050359416125192,0.000006611710560964397077757753164
N = 8,1.284025416676960294208829365,1.2840254166877414,1.078110017486338512519210577E-11,8.396329258554864877541478439E-12
N = 16,1.284025416687741484073420401,1.2840254166877414,8.968972765087480789422988892E-17,6.985043012796233908793933704E-17
N = 32,1.284025416687741484073420567,1.2840254166877414,8.968972781687480789422988892E-17,6.985043025724326907779255420E-17
N = 64,1.284025416687741484073420567,1.2840254166877414,8.968972781687480789422988892E-17,6.985043025724326907779255420E-17
N = 128,1.284025416687741484073420567,1.2840254166877414,8.968972781687480789422988892E-17,6.985043025724326907779255420E-17
N = 256,1.284025416687741484073420567,1.2840254166877414,8.968972781687480789422988892E-17,6.985043025724326907779255420E-17

In [22]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[4])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 1/2:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 4
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 1/2:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,1.5,1.6487212707001282,0.1487212707001281941643355822,0.09020401043104989070400221872
N = 2,1.625,1.6487212707001282,0.02372127070012819416433558217,0.01438767796697071492933573693
N = 3,1.645833333333333333333333333,1.6487212707001282,0.002887937366794860831002249172,0.001751622556290852300224656833
N = 4,1.648437500000000000000000000,1.6487212707001282,0.0002837707001281941643355821725,0.0001721156299558694715857715946
N = 8,1.648721265035962301587301587,1.6487212707001282,5.664165892577033995172498107E-9,3.435490275546545470651300307E-9
N = 16,1.648721270700128146826589163,1.6487212707001282,4.733774641917249810695648193E-17,2.871179456493004498388901377E-17
N = 32,1.648721270700128146848650786,1.6487212707001282,4.731568479617249810695648193E-17,2.869841351417752357734428237E-17
N = 64,1.648721270700128146848650786,1.6487212707001282,4.731568479617249810695648193E-17,2.869841351417752357734428237E-17
N = 128,1.648721270700128146848650786,1.6487212707001282,4.731568479617249810695648193E-17,2.869841351417752357734428237E-17
N = 256,1.648721270700128146848650786,1.6487212707001282,4.731568479617249810695648193E-17,2.869841351417752357734428237E-17

In [23]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[5])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 1:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 5
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 1:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,2,2.718281828459045,0.7182818284590450907955982984,0.2642411176571153176795461492
N = 2,2.5,2.718281828459045,0.2182818284590450907955982984,0.08030139707139414709943268651
N = 3,2.666666666666666666666666667,2.718281828459045,0.05161516179237842412893163143,0.01898815687615375690606153217
N = 4,2.708333333333333333333333334,2.718281828459045,0.009948495125711757462264964428,0.003659846827343659357718743484
N = 8,2.718278769841269841269841271,2.718281828459045,0.000003058617775249525757027427649,0.000001125202597915835763113415382
N = 16,2.718281828459042259058793453,2.718281828459045,2.831736804845427648842334747E-15,1.041737753311141602234343145E-15
N = 32,2.718281828459045235360287474,2.718281828459045,1.445646891755723511576652527E-16,5.318237706703281616029823559E-17
N = 64,2.718281828459045235360287474,2.718281828459045,1.445646891755723511576652527E-16,5.318237706703281616029823559E-17
N = 128,2.718281828459045235360287474,2.718281828459045,1.445646891755723511576652527E-16,5.318237706703281616029823559E-17
N = 256,2.718281828459045235360287474,2.718281828459045,1.445646891755723511576652527E-16,5.318237706703281616029823559E-17

In [24]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[6])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 2:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 6
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 2:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,3,7.38905609893065,4.389056098930650406941822439,0.5939941502901619341925885589
N = 2,5,7.38905609893065,2.389056098930650406941822439,0.3233235838169365569876475982
N = 3,6.333333333333333333333333333,7.38905609893065,1.055722765597317073608489106,0.1428765395014529721843536245
N = 4,7.000000000000000000000000000,7.38905609893065,0.3890560989306504069418224390,0.05265301734371117978270663750
N = 8,7.387301587301587301587301587,7.38905609893065,0.001754511629063105354520851966,0.0002374473282611861017498165737
N = 16,7.389056098516415976733437051,7.38905609893065,4.142344302083853879664828777E-10,5.606053393860870769682723770E-11
N = 32,7.389056098930650227230427459,7.38905609893065,1.797113949799664828777313232E-16,2.432129254046053962948280915E-17
N = 64,7.389056098930650227230427460,7.38905609893065,1.797113949789664828777313232E-16,2.432129254032520434624619646E-17
N = 128,7.389056098930650227230427460,7.38905609893065,1.797113949789664828777313232E-16,2.432129254032520434624619646E-17
N = 256,7.389056098930650227230427460,7.38905609893065,1.797113949789664828777313232E-16,2.432129254032520434624619646E-17

In [25]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(ex_sum_arr[0])],
    'Exact Value':[str(true_ex[7])],
    'Absolute Error':[str(abs_err_ex[0])],
    'Relative Error':[str(rel_err_ex[0])] 
}
print('For exp(x) when x = 4:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 7
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (ex_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_ex[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_ex[temp])
    temp = temp + 8
df

For exp(x) when x = 4:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,5,54.598150033144236,49.59815003314423620395245962,0.9084218055563290937105472480
N = 2,13,54.598150033144236,41.59815003314423620395245962,0.7618966944464556436474228448
N = 3,23.66666666666666666666666667,54.598150033144236,30.93148336647756953728579295,0.5665298796332910435632569739
N = 4,34.33333333333333333333333334,54.598150033144236,20.26481669981090287061912628,0.3711630648201264434790911029
N = 8,53.43174603174603174603174604,54.598150033144236,1.166404001398204457920713578,0.02136343448798411189982268629
N = 16,54.59808818263844718871173899,54.598150033144236,0.00006185050578901524072062844921,0.000001132831529117166148308769547
N = 32,54.59815003314423906848451197,54.598150033144236,2.864532052351550788879394531E-15,5.246573465607560122136977794E-17
N = 64,54.59815003314423907811026118,54.598150033144236,2.874157801561550788879394531E-15,5.264203640263947954451291471E-17
N = 128,54.59815003314423907811026118,54.598150033144236,2.874157801561550788879394531E-15,5.264203640263947954451291471E-17
N = 256,54.59815003314423907811026118,54.598150033144236,2.874157801561550788879394531E-15,5.264203640263947954451291471E-17

In [26]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(log_sum_arr[0])],
    'Exact Value':[str(true_log[0])],
    'Absolute Error':[str(abs_err_log[0])],
    'Relative Error':[str(rel_err_log[0])] 
}
print('For log(x) when x = 1/32:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 0
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (log_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_log[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_log[temp])
    temp = temp + 5
df

For log(x) when x = 1/32:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,-0.03125,-0.0317486983145803,0.0004986983145802981187699742804,-0.01570767751291634838075092413
N = 2,-0.03173828125,-0.0317486983145803,0.00001041706458029811876997428044,-0.0003281099740556663242001573231
N = 3,-0.03174845377604166666666666667,-0.0317486983145803,2.445385386314521033076104398E-7,-0.000007702316996068781355349576257
N = 4,-0.03174869219462076822916666667,-0.0317486983145803,6.119959529889603307610439783E-9,-1.927625337344639449243971499E-7
N = 8,-0.03174869831457705177377820724,-0.0317486983145803,3.246344991767040439782887697E-15,-1.022512784493021660975216269E-13
N = 16,-0.03174869831458030115699628117,-0.0317486983145803,3.038226306889560217112302780E-18,-9.569609049118976600530319729E-17
N = 32,-0.03174869831458030115699628273,-0.0317486983145803,3.038226308449560217112302780E-18,-9.569609054032563874385841318E-17
N = 64,-0.03174869831458030115699628273,-0.0317486983145803,3.038226308449560217112302780E-18,-9.569609054032563874385841318E-17
N = 128,-0.03174869831458030115699628273,-0.0317486983145803,3.038226308449560217112302780E-18,-9.569609054032563874385841318E-17
N = 256,-0.03174869831458030115699628273,-0.0317486983145803,3.038226308449560217112302780E-18,-9.569609054032563874385841318E-17

In [27]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(log_sum_arr[0])],
    'Exact Value':[str(true_log[1])],
    'Absolute Error':[str(abs_err_log[0])],
    'Relative Error':[str(rel_err_log[0])] 
}
print('For log(x) when x = 1/16:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 1
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (log_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_log[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_log[temp])
    temp = temp + 5
df

For log(x) when x = 1/16:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,-0.0625,-0.06453852113757118,0.002038521137571178143410577377,-0.03158611479841378945792353794
N = 2,-0.064453125,-0.06453852113757118,0.00008539613757117814341057737693,-0.001323180885864220378483648496
N = 3,-0.06453450520833333333333333333,-0.06453852113757118,0.000004015929237844810077244046926,-0.00006222530617465500017365315394
N = 4,-0.06453831990559895833333333333,-0.06453852113757118,2.012319722198100772440469261E-7,-0.000003118013376706623065372119884
N = 8,-0.06453852113585786095687321254,-0.06453852113757118,1.713317186537364836926084980E-12,-2.654720245115680477569057173E-11
N = 16,-0.06453852113757117167271210892,-0.06453852113757118,6.470698468456926084980368614E-18,-1.002610279009012052628852565E-16
N = 32,-0.06453852113757117167292391569,-0.06453852113757118,6.470486661686926084980368614E-18,-1.002577460350284420824991531E-16
N = 64,-0.06453852113757117167292391569,-0.06453852113757118,6.470486661686926084980368614E-18,-1.002577460350284420824991531E-16
N = 128,-0.06453852113757117167292391569,-0.06453852113757118,6.470486661686926084980368614E-18,-1.002577460350284420824991531E-16
N = 256,-0.06453852113757117167292391569,-0.06453852113757118,6.470486661686926084980368614E-18,-1.002577460350284420824991531E-16

In [28]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(log_sum_arr[0])],
    'Exact Value':[str(true_log[2])],
    'Absolute Error':[str(abs_err_log[0])],
    'Relative Error':[str(rel_err_log[0])] 
}
print('For log(x) when x = 1/8:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 2
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (log_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_log[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_log[temp])
    temp = temp + 5
df

For log(x) when x = 1/8:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,-0.125,-0.13353139262452263,0.008531392624522626810801284591,-0.06389053882267279649798146666
N = 2,-0.1328125,-0.13353139262452263,0.0007188926245226268108012845914,-0.005383697499089846279105308324
N = 3,-0.1334635416666666666666666667,-0.13353139262452263,0.00006785095785596014413461789143,-0.0005081273887912670941989615470
N = 4,-0.1335245768229166666666666667,-0.13353139262452263,0.000006815801605960144134617891435,-0.00005104269095077529561399156005
N = 8,-0.1335313916915938967750186013,-0.13353139262452263,9.329287300357826832914345235E-10,-6.986587286325157449064107389E-9
N = 16,-0.1335313926245225935250604753,-0.13353139262452263,3.328574080929143452346324921E-17,-2.492727751509918071830451148E-16
N = 32,-0.1335313926245226231463436210,-0.13353139262452263,3.664457663591434523463249207E-18,-2.744266791177364100649746999E-17
N = 64,-0.1335313926245226231463436210,-0.13353139262452263,3.664457663591434523463249207E-18,-2.744266791177364100649746999E-17
N = 128,-0.1335313926245226231463436210,-0.13353139262452263,3.664457663591434523463249207E-18,-2.744266791177364100649746999E-17
N = 256,-0.1335313926245226231463436210,-0.13353139262452263,3.664457663591434523463249207E-18,-2.744266791177364100649746999E-17

In [29]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(log_sum_arr[0])],
    'Exact Value':[str(true_log[3])],
    'Absolute Error':[str(abs_err_log[0])],
    'Relative Error':[str(rel_err_log[0])] 
}
print('For log(x) when x = 1/4:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 3
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (log_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_log[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_log[temp])
    temp = temp + 5
df

For log(x) when x = 1/4:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,-0.25,-0.2876820724517809,0.03768207245178090136761284157,-0.1309851258044481936501384505
N = 2,-0.28125,-0.2876820724517809,0.006432072451780901367612841568,-0.02235826653000421785640575684
N = 3,-0.2864583333333333333333333333,-0.2876820724517809,0.001223739118447568034279508268,-0.004253789984263555224116974671
N = 4,-0.2874348958333333333333333333,-0.2876820724517809,0.0002471766184475680342795082682,-0.0008592006319371809805628279944
N = 8,-0.2876815250941685267857142857,-0.2876820724517809,5.473576123745818985558681887E-7,-0.000001902647626630699596781621588
N = 16,-0.2876820724472973365673665293,-0.2876820724517809,4.483564800246312268188741803E-12,-1.558513800333461368111806481E-11
N = 32,-0.2876820724517809274386766978,-0.2876820724517809,2.607106385623181125819683075E-17,-9.062456910866994082352967274E-17
N = 64,-0.2876820724517809274392190056,-0.2876820724517809,2.607160616403181125819683075E-17,-9.062645420284830988940922322E-17
N = 128,-0.2876820724517809274392190056,-0.2876820724517809,2.607160616403181125819683075E-17,-9.062645420284830988940922322E-17
N = 256,-0.2876820724517809274392190056,-0.2876820724517809,2.607160616403181125819683075E-17,-9.062645420284830988940922322E-17

In [30]:
import pandas as pd
import numpy as np
 
#Create a DataFrame
d = {
    'Calculated Sum':[str(log_sum_arr[0])],
    'Exact Value':[str(true_log[4])],
    'Absolute Error':[str(abs_err_log[0])],
    'Relative Error':[str(rel_err_log[0])] 
}
print('For log(x) when x = 1/2:') 
df = pd.DataFrame(d,columns=['Calculated Sum','Exact Value','Absolute Error','Relative Error'],index=['N = 1', 'N = 2', 'N = 3', 'N = 4', 'N = 8', 'N = 16','N = 32','N = 64', 'N = 128', 'N = 256'])
temp = 4
for row in df.index:
    for column in df.columns:
        if column == 'Exact Value':
            continue
        if column == 'Calculated Sum':
            df.at[row,column] = (log_sum_arr[temp])
        if column == 'Absolute Error':
            df.at[row,column] = (abs_err_log[temp])
        if column == 'Relative Error':
            df.at[row,column] = (rel_err_log[temp])
    temp = temp + 5
df

For log(x) when x = 1/2:

,Calculated Sum,Exact Value,Absolute Error,Relative Error
N = 1,-0.5,-0.6931471805599453,0.1931471805599452862267639830,-0.2786524795555182721860771403
N = 2,-0.625,-0.6931471805599453,0.06814718055994528622676398300,-0.09831559944439784023259642538
N = 3,-0.6666666666666666666666666667,-0.6931471805599453,0.02648051389327861956009731630,-0.03820330607402436291476952036
N = 4,-0.6822916666666666666666666667,-0.6931471805599453,0.01085551389327861956009731630,-0.01566119606013430892058443099
N = 8,-0.6927501860119047619047619048,-0.6931471805599453,0.0003969945480405243220020781952,-0.0005727420657180198036432803908
N = 16,-0.6931463282650034969370906872,-0.6931471805599453,8.522949417892896732957951804E-7,-0.000001229601685894155993454204720
N = 32,-0.6931471805530863849148397652,-0.6931471805599453,6.858901311924217795180413127E-12,-9.895302908659874481045035101E-12
N = 64,-0.6931471805599453094164103949,-0.6931471805599453,2.318964641190481958687305450E-17,-3.345558787842362837919138662E-17
N = 128,-0.6931471805599453094172321214,-0.6931471805599453,2.319046813840481958687305450E-17,-3.345677337917014542402040760E-17
N = 256,-0.6931471805599453094172321214,-0.6931471805599453,2.319046813840481958687305450E-17,-3.345677337917014542402040760E-17

As seen from the results above, as "N", the number of terms used in the Taylor Polynomial summation, increases, the closer the calculated results are to the actual results. Another interesting observation that can be made is that if the x term increases, getting further from the point at which the Taylor Polynomial is centered, the less accurate the results become with a lower number of "N" terms. For example, when x = 4 and N = 1 for exp(x), the calculated and exact values differ by a sizable margin. This is due to the fact that the Taylor Polynomial is centered at 0, so x values further from 0 will need more "N" values to approach the actual value of the function at that x value.